export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_TEAMWORK_DATA = 'LOAD_TEAMWORK_DATA';
export const LOAD_PROJECTS_FROM_DB = 'LOAD_PROJECTS_FROM_DB';
export const LOAD_INVITES = 'LOAD_INVITES';
export const ADD_INVITE = 'ADD_INVITE';
export const REMOVE_INVITE = 'REMOVE_INVITE';
