export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_TEAMWORK_DATA = 'LOAD_TEAMWORK_DATA';
export const LOAD_PROJECTS_FROM_DB = 'LOAD_PROJECTS_FROM_DB';
